# versinons need updating
name: inspectsf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - opencv
  - scikit-learn
  - tqdm
  - rawpy
  - imageio
  - exifread
  - pytz
  - pyyaml
  - pip
  - colour-demosaicing
  - reportlab
  - pip:
      - omegaconf
