# versinons need updating
name: inspectsf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - opencv
  - scikit-learn
  - tqdm
  - imageio
  - exifread
  - pytz
  - pyyaml
  - pip
  - colour-demosaicing
  - reportlab
  - pip:
      - omegaconf
      - rawpy
