# Hydra defaults and settings. Ignore these (don't change)
defaults:
  - _self_
  - paths: default

tasks:
  - inspect_bbotv31_unpreprocessed
  - report
  # - inspect_developed # Only for bbot developed images

batch_id: NC_2025-02-17

inspect_v31:  
  sample_size: 50
  sample_strategy: random # random, first, last, middle
  bit_depth: 8  # 8 or 16
  concurrent_workers: 8  # Number of threads for concurrent processing
  image_height: 9528 # Don't change this
  image_width: 13376 # Don't change this
  random_seed: 42

  downscale:
    factor: 0.25
    remove_local_raws: true

inspect_developed:
  downscale_factor: 0.25
  remove_jpgs: true # Remove jpgs after downscaling
  sample_size: 10
  sample_strategy: random # random, first, last, middle