root_dir: ${hydra:runtime.cwd}

data_dir: ${paths.root_dir}/data

primary_storage: /mnt/research-projects/s/screberg/longterm_images2
secondary_storage: /mnt/research-projects/s/screberg/longterm_images
tertiary_storage: /mnt/research-projects/s/screberg/GROW_DATA

local_upload: ${paths.data_dir}/semifield-upload
color_matrix: ${paths.data_dir}/semifield-utils/image_development/color_matrix/transformation_matrix.npz