root_dir: ${hydra:runtime.cwd}

primary_storage_uploads: /mnt/research-projects/s/screberg/longterm_images2/semifield-upload

local_upload: ${paths.root_dir}/data/semifield-upload
color_matrix: ${paths.root_dir}/data/semifield-utils/image_development/color_matrix/transformation_matrix.npz