# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/${now:%Y-%m-%d}/${task}/${now:%H-%M-%S}/

job_logging:
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      formatter: simple
      filename: ${hydra.runtime.output_dir}/SEMIF_REPORT.log
  
  formatters:
    simple:
      format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'

  root:
    handlers:
      - console
      - file
  disable_existing_loggers: false